controllers:
  resource: ../../src/Controller/
  type: attribute

controllers_admin:
  prefix: '/admin'
  resource: ../../src/Controller/Admin
  type: attribute

kernel:
  resource: ../../src/Kernel.php
  type: attribute