controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

controllers_admin:
    prefix: '/admin'
    resource: ../src/Controller/Admin
    type: attribute